name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Run linting
        run: |
          cd frontend
          npm run lint

      - name: Build project
        run: |
          cd frontend
          npm run build